version: "3.9"

services:
  consul:
    image: hashicorp/consul:1.16.2
    container_name: consul
    ports:
      - "8500:8500"   # Consul UI / HTTP API
    networks:
      - backend

  account-service:
    build:
      context: .
      dockerfile: Account/ChatRumi.Account.Api/Dockerfile
    container_name: account-service
    ports:
      - "5049:5049"
    environment:
      - ASPNETCORE_URLS=http://+:5049
      - Consul__ServiceName=account-service
      - Consul__ServiceAddress=http://account-service:5049
      - Consul__Host=consul
      - Consul__Port=8500
    depends_on:
      - consul
    networks:
      - backend

  chat-service:
    build:
      context: .
      dockerfile: Chat/ChatRumi.Chat.Api/Dockerfile
    container_name: chat-service
    ports:
      - "5111:5111"
    environment:
      - ASPNETCORE_URLS=http://+:5111
      - Consul__ServiceName=chat-service
      - Consul__ServiceAddress=http://chat-service:5111
      - Consul__Host=consul
      - Consul__Port=8500
    depends_on:
      - consul
    networks:
      - backend

  friendship-service:
    build:
      context: .
      dockerfile: Friendship/ChatRumi.Friendship.Api/Dockerfile
    container_name: friendship-service
    ports:
      - "5031:5031"
    environment:
      - ASPNETCORE_URLS=http://+:5031
      - Consul__ServiceName=friendship-service
      - Consul__ServiceAddress=http://friendship-service:5031
      - Consul__Host=consul
      - Consul__Port=8500
    depends_on:
      - consul
    networks:
      - backend
  
  feed-service:
    build:
      context: .
      dockerfile: Friendship/ChatRumi.Feed.Api/Dockerfile
    container_name: feed-service
    ports:
      - "5031:5031"
    environment:
      - ASPNETCORE_URLS=http://+:5211
      - Consul__ServiceName=feed-service
      - Consul__ServiceAddress=http://feed-service:5211
      - Consul__Host=consul
      - Consul__Port=8500
    depends_on:
      - consul
    networks:
      - backend

  gateway:
    build:
      context: .
      dockerfile: ChatRum.Gateway/Dockerfile
    container_name: gateway
    ports:
      - "7000:7000"
    environment:
      - ASPNETCORE_URLS=http://+:7000
    depends_on:
      - consul
      - account-service
      - chat-service
      - friendship-service
      - feed-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
